-- Opprett abonnementer tabell
create table abonnementer (
  id bigint generated by default as identity primary key,
  etternavn text,
  adresse text,
  sted text,
  kommune text,
  var text,
  host text,
  epost text,
  fakturert text,
  mail_var text,
  mail_host text,
  tidsbruk_slatt text,
  fornyelsesdato text,
  sum text,
  notat text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Opprett indekser for bedre ytelse
create index idx_abonnementer_etternavn on abonnementer(etternavn);
create index idx_abonnementer_adresse on abonnementer(adresse); 